package com.example.pma;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import com.example.pma.R;

public class MainActivity2 extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        RecyclerView rec = findViewById(R.id.recV);
        rec.setHasFixedSize(true);
        rec.setLayoutManager(new LinearLayoutManager(this));

        Turizam[] tur = new Turizam[]{
                new Turizam("Vrnjacka Banja","Opsta ocena: 3.8⭐","Broj dana: 3",R.drawable.vrnjacka,"Kraljica banjskog turizma, kako neformalno nazivaju Vrnjačku Banju, od davnina je bila poznata po svojim lekovitim izvorima. Ovo područje je bilo naseljeno još u praistoriji. Arheološki nalazi, oruđe iz mlađeg kamenog doba, otkrivaju mogućnost da su i praistorijski ljudi koristili banjske izvore. O lekovitosti vode u Vrnjačkoj Banji prvi put se može čuti u doba Rimljana. Oni su na ovom mestu izgradili lečilište Aquae Orcinae, i izvor tople vode Fons Romanus. Veruje se da su prethodno i starosedeoci, keltsko pleme Skordisci, koristili vodu sa izvora za piće, kupanje i lečenje. Koliko je banjska voda bila čuvena u antičko doba, najviše govore brojni zlatnici."),
                new Turizam("Tara","Opsta ocena: 4.0⭐","Broj dana: 4",R.drawable.tara,"Tara predstavlja planinu koja se može pohvaliti netaknutim prirodnim lepotama i brižljivim održavanjem pravog planinskog ambijenta. Pored toga, ova planina sve više razvija svoju turističku ponudu i svojim posetiocima nudi raznovrsne sadržaje i aktivnosti. Na našoj stranici možete pronaći sve najbitnije informacije o ovoj turističkoj destinaciji, rezervisati odličan smeštaj ili se upoznati sa ponudom najpoznatijih restorana. Ovde možete videti koje su ture, atrakcije i sadržaji najpoznatiji na planini. Istražite celokupnu ponudu i u potpunosti organizujte svoj planinski odmor.Na osnovu dugogodišnjih proučavanja i istraživanja ovog područja, a radi zaštite izuzetnih vrednosti."),
                new Turizam("Djavolja Varos","Opsta ocena: 4.6⭐","Broj dana: 2",R.drawable.djavoljavaros,"Spomenik prirode „Đavolja Varoš“ nalazi se na jugu Srbije, 27 km jugoistočno od Kuršumlije, a 89 km jugozapadno od Niša. Od Beograda je udaljen 288 km. Ovaj prirodni spomenik čine dva, u svetu retka, prirodna fenomena: zemljane figure, kao specifični oblici reljefa koji u prostoru deluju vrlo atraktivno, i dva izvora jako kisele vode sa visokom mineralizacijom.Ova dva u svetu retka prirodna fenomena posmatrana zajedno „Đavolju Varoš“ čine pravim svetskim čudom prirode. Atraktivnost dva neviđena čuda prirode dopunjuju okolni prirodni ambijent koji oko zemljanih figura deluje surovo, skoro mistično, a u širem okruženju živopisno i pitomo, kao i ostaci naselja."),
                new Turizam("Golubacka Tvrdjava","Opsta ocena: 5.0⭐","Broj dana: 4",R.drawable.golubac,"Golubačka tvrđava je izgrađena na ostacima starog rimskog utvrđenja. I dan danas nije poznata tačna godina kada je ova tvrđava izgrađena. Na osnovu svih pronađenih dokaza, još uvek je nemoguće utvrditi ko je izgradio tvrđavu, Srbi ili Ugari. Golubački grad je dograđivan sve do kraja petnaestog veka, kada je dobio svoj konačan izgled. Prvi put i istoriji, Golubac se pominje u ugarskim izvorima daleke 1335. godine. Vlast nad tvrđavom smenjivala se između Ugara, Srba i Turaka sve do 1481. godine, kada je Turci osvajaju po drugi put i započinju svoju viševekovnu vladavinu. Vladavina Osmanskog carstva prekida se nakon Drugog srpskog ustanka napokon predat srpskoj vlasti"),
                new Turizam("Sumarice","Opsta ocena: 4.7⭐","Broj dana: 1",R.drawable.sumarice,"Memorijalni park Šumarice predstavlja važan deo srpske istorije i privlači veliku pažnju turista, kako stranih tako i lokalnih, a najviše zbog tragičnih i sentimentalnih događaja kojima ovaj park odaje počast. Uz to, Šumarice su i popularno izletište i odmaralište jer nude pozamašan broj zanimljivih aktivnosti, a istovremeno i prirodne prostore, savršene za predah i opuštanje.Istorija Šumarica nije svetla. Na ovom mestu u Drugom svetskom ratu, tačnije 21. oktobra 1941. godine, nemački okupatori su streljali oko 3000 civila, među kojima je bilo 300 učenika kragujevačkih srednjih škola.Pored spomenika, na ulazu u park, podignut je i spomen-muzej “21. oktobar."),
                new Turizam("Petrovaradin","Opsta ocena: 5.0⭐","Broj dana: 4",R.drawable.pet,"U periodu od 1692. do 1780. godine Austrija je izgradila čuveni Gibraltar na Dunavu, nazvan tako zbog svoje veličine i dominantnosti (112 hektara površine i podzemni hodnici dužine 16 kilometara). I danas predstavlja jedno od najbolje očuvanih artiljerihskih bastionih utvrđenja ovog dela Evrope.Nalazi arheoloških istraživanja svedoče o prisustvu paleolitske kulture, a potvrđeni su i ostaci iz mlađeg kamenog doba.Danas je Tvrđava umetnički centar sa mnoštvom ateljea priznatih umetnika, Akademijom umetnosti, uređenim stazama i podzemnim hodnicima koji privlače brojne posetioce grada. Bastione trase doprinele su atraktivnosti čuvenog Jelisavetinog Bastiona."),
                new Turizam("Sokobanja","Opsta ocena: 2.8⭐","Broj dana: 1",R.drawable.sb,"Za Sokobanju se spravom može reći da je gospodar banjskog turizma u Srbiji i da je srpska kraljica turizma. Čist vazduh, kvalitetne termalne vode, mnoštvo parkova su idealno mesto za lečenje plućnih bolesti, reumatska oboljenja, nervno obolele osobe, a pogotovo se preporučuje za odmor i rekreaciju.Turizmom se Sokobanja bavi punih 180 godina a u zadnjih desetak godina se razvija velikom brzinom zbog priliva zdravog kapitala i izgradnjom akva parka Podina i wellness centra, tako da pored zdravstenog turizma sa stopostotnim uspehom u lečenju Soko Banja ima i rekreativno komercijalni turizam. Smeštaj u hotelima i apartmanima, banja pod Ozrenom beleži iz godine u godinu."),
                new Turizam("Kopaonik","Opsta ocena: 4.4⭐","Broj dana: 5",R.drawable.kop,"Kopaonik (poznat i kao Srebrna planina) je najveći planinski masiv u južnoj Srbiji koji se pruža od severozapada ka jugoistoku dužinom od oko 75 km, dosežući u srednjem delu širinu od oko 40 km. Jedan njegov deo je zaštićena zona pod imenom nacionalni park Kopaonik u okviru koga postoji veći broj zaštićenih prirodnih celina, a na njemu se nalazi i najveći skijaški centar u Srbiji. Njegov najviši vrh je Pančićev vrh sa 2017 m nmv. na kome se nalazi mauzolej čuvenog srpskog prirodnjaka po kome je dobio ime, oko koga se nalazi baza vojske Srbije. Kopaonik predstavlja jednu od najpopularnijih turističkih destinacija u Srbiji.Njegovo jezgro sačinjeno je od intruzivne mase granita."),
                new Turizam("Kalemegdan","Opsta ocena: 3.7⭐","Broj dana: 1",R.drawable.kalis,"Kalemegdan je najveći beogradski park. Istovremeno je najznačajniji kulturno-istorijski kompleks, u kojem dominira Beogradska tvrđava iznad ušća Save u Dunav. Naziv Kalemegdan odnosi se samo na prostorni plato oko tvrđave koji je osamdesetih godina 19. veka pretvoren u park .Plato je, dok je tvrđava bila glavno vojno uporište Beograda, služio da se neprijatelj osmotri i sačeka za borbu. Njegovo ime potiče od turskih reči kale („tvrđava“) i mejdan („bojište“). Turci su Kalemegdan nazivali i Fićir-bajir što znači „breg za razmišljanje“.Preuređivanje u park otpočelo je, posle predaje tvrđave Srbima (1867), po naređenju kneza Mihaila Obrenovića.Na Kalemegdanu je otkrivena J.C"),
                new Turizam("Zlatibor","Opsta ocena: 3.8⭐","Broj dana: 4",R.drawable.zlatibor,"Zlatiborska narodna nošnja je kombinacija crnogorske i šumadijske. Muškarci su ljeti išli u prtištu, tj. dugačkim gaćama i košuljama od konoplje, a ponekad u pelengirima od vune. Oko struka su stavljali pojas, a preko njega silaje sa zataknutim pištoljem i britvom. Na nogama su imali opanke sa vezenim čarapama do koljena i tozlucima, tj. tkanim kamašnama, dok su na glavi nosili šajkaču ili šubaru. Zimi su dodavali koporan, a u svečanim prilikama oblačili su ljepše odijelo. Žene su nosile široke suknje, po dnu izvezene srmom i zubune od bijelog sukna, takođe izvezene srmom i metalnim šljokicama.Zlatiborski melos potiče iz prapostojbine,kojim se izvode narodne pesme."),
        };
        Adapter adapter = new Adapter(tur,MainActivity2.this);
        rec.setAdapter(adapter);
    }
}